name: Deploy Laravel ke InfinityFree
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil Kode dari GitHub
      uses: actions/checkout@v4

    - name: Setup PHP 8.2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, json, pdo, pdo_sqlite, sqlite3

    - name: Install Vendor Composer & Build Vite
      run: |
        composer install --no-dev --optimize-autoloader --ignore-platform-reqs --no-interaction
        if [ -f "package.json" ]; then
          npm install
          npm run build || true
          rm -rf node_modules
        fi

    - name: Siapkan File .env & Database SQLite
      run: |
        mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache/data storage/logs bootstrap/cache database
        chmod -R 777 storage bootstrap/cache database
        if [ ! -f "database/database.sqlite" ]; then
          touch database/database.sqlite
        fi
        cat << 'EOF' > .htaccess
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteRule ^(.*)$ public/$1 [L]
        </IfModule>
        EOF
        echo "APP_NAME=Laravel" > .env
        echo "APP_ENV=production" >> .env
        echo "APP_KEY=base64:P43KETVbaYBQqKQchzIn7vQjJyR4O3H456c0tBYDajE=" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_URL=http://afl3ccds.site.je" >> .env
        echo "DB_CONNECTION=sqlite" >> .env
        echo "SESSION_DRIVER=file" >> .env
        echo "CACHE_STORE=file" >> .env
        echo "LOG_CHANNEL=stderr" >> .env
        php artisan migrate --force || true

    - name: Upload Otomatis ke htdocs InfinityFree
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -c "set ftp:ssl-allow no; set net:timeout 30; set net:max-retries 3; open -u if0_43118831,xTXmBkXfpLD ftpupload.net; mirror -R --parallel=10 --exclude-glob .git* --exclude-glob node_modules/ . /htdocs/"
